!DDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAANNNNNNNNNNNNNNNNNNNNNNNNSSSSSSSSSSSSSSSSSSSSSSSSSS
!//             /////////////       ////////////////    ////////     //////    ////////////////        //!
!//             /////////////      ////////////////    //////////   //////    ////////////////         //!
!//            /////    /////     //////    //////    //////////// //////    /////                     //!
!//           /////    //////    ////////////////    ///////////////////    ////////////////           //!
!//          /////    //////    ////////////////    ////// ////////////               /////            //!
!//         ///////////////    //////    //////    //////   //////////    ////////////////             //!
!//       ///////////////     //////    //////    //////     ////////    ////////////////              //!
!//          Developer            Assistant    in      Numerical             Sciences                  //!
!//----------------------------------------------------------------------------------------------------//!
!// Supervisor: Dr. h. hdhrnuidn, Aerospace Department, Amirkabir University of Technology           //!
!// Chief Developer: N. msnkre, Aerospace eng., Amirkabir University of Technology                     //!
!// Date: October, 14, 2013                                                                            //!
!//                                                                                                    //!
!// The Program is Available Through the Website: www.DANS.ir                                          //!
!// It May be Copied, Modified and Redistributed for Non-Commercial Use.                               //!
!//----------------------------------------------------------------------------------------------------//!
!// Description:                                                                                       //!
!// In most of common problems in computational fluid dynamics, commercial software are necessary for  //!
!// mesh generation .These meshes can be used in Computational Fluid Dynamic Codes. So an interface    //!
!// code is required for converting meshes from commercial software to desired form. A standard format //!
!// which is known as STL is common between CAD type software. In this code two/three dimensional STL  //!
!// format of mesh generated by ANSYS/ICEM analyzed then the data of the elements of this code         //!
!// extracted. In the view of the fact that solving two dimensional flow, three dimensional boundary   //!
!// layer mesh or development methods of generating three dimensional meshes, demand a computational   //!
!// mesh with same direction, so in this code all elements will be located in same directions.         //!
!// Therefore in two dimensional meshes direction of elements are outside of the surface and in three  //!
!// dimensional meshes direction tend to be in opposite side.                                          //!
!////////////////////////////////////////////////////////////////////////////////////////////////////////!
!*********************************************************************************************************
 Program ReadSTLFile
 Implicit None
!*********************************************************************************************
!=============================
 Integer,Parameter::Dim=10000
!=============================

 Integer::NP  !Number of Existing Points
 Integer::NC !Number of Cells of mesh
 Integer::FirstOE !Index of First Oriented Element
 Integer,Dimension(1:4,1:Dim)::Corn !Corners point index of Each Cell 
 Integer,Dimension(1:4,1:Dim)::Neib !Neighboring Cell Index of Each Elements 
 Real(8),Dimension(1:Dim)::X,Y,Z !Coordinate of Points Constructing Mesh
!************************************** Main *********************************************** 
!Part 1:
 Call Read_STL(Dim,NP,NC,Corn,X,Y,Z)

!Part 2:
 Call Find_Neib(Dim,NC,Corn,Neib)

!part 3:
 Call First_Elem_Orient(Dim,X,Y,Z,NC,Corn,Neib,FirstOE)

!part 4:
 Call Equalize_Orient(Dim,FirstOE,NC,Corn,Neib)
      
!part 5:
 Call WritePlaneMesh_cgid_plt(Dim,NP,NC,Corn,X,Y,Z)
 
 print*,'Finished'
 pause
!*********************************************************************************************
 End
!###########################################################################################
