!DDDDDDDDDDDDDDDDDDDDDDDDDDDAAAAAAAAAAAAAAAAAAAAAAAAAAAANNNNNNNNNNNNNNNNNNNNNNNNSSSSSSSSSSSSSSSSSSSSSSSSSS
!//             /////////////       ////////////////    ////////     //////    ////////////////        //!
!//             /////////////      ////////////////    //////////   //////    ////////////////         //!
!//            /////    /////     //////    //////    //////////// //////    /////                     //!
!//           /////    //////    ////////////////    ///////////////////    ////////////////           //!
!//          /////    //////    ////////////////    ////// ////////////               /////            //!
!//         ///////////////    //////    //////    //////   //////////    ////////////////             //!
!//       ///////////////     //////    //////    //////     ////////    ////////////////              //!
!//          Developer            Assistant    in      Numerical             Sciences                  //!
!//----------------------------------------------------------------------------------------------------//!
!// Supervisor: Dr. h. hdhrnuidn, Aerospace Department, Amirkabir University of Technology           //!
!// Chief Developer: N. msnkre, Aerospace eng., Amirkabir University of Technology                     //!
!// Date: October, 14, 2013                                                                            //!
!//                                                                                                    //!
!// The Program is Available Through the Website: www.DANS.ir                                          //!
!// It May be Copied, Modified and Redistributed for Non-Commercial Use.                               //!
!//----------------------------------------------------------------------------------------------------//!
!// Description:                                                                                       //!
!// Due to the fact that commercial software for generating mesh are commonly used by researchers in   //!
!// computational fluid dynamic filed, development a code for analyzing and decoding output of these   //!
!// software is crucial. Therefore in this code MSH format of mesh generated by GAMBIT or ICEM         //!
!// investigated then the MSH format changed to desirable format for using in Computational Fluid      //!
!// Dynamic codes. In the second phase of this code, meshes generated by mesh generation codes         //!
!// converted to MSH format. This format is acceptable in most common analyzer software such as FLUENT.//!
!////////////////////////////////////////////////////////////////////////////////////////////////////////!
!*********************************************************************************************************
 Program ReadMeshFile
 Implicit None
!*********************************************************************************************
!=============================
 Integer,Parameter::Dim=8000000
 Integer,Parameter::DimIDS=6 !first dimension if IDS array (2D=4 , 3D=6)
!=============================
 Integer::NP  !Number of Existing Points
 Integer::NC !Number of Cells of mesh
 Integer::NF !Number of Faces Constructing Mesh  !Number of Faces Constructing Mesh 
 Integer::NR   !Number Of Regions of mesh
 Integer::MeshDim !Mesh Dimension (2D=2 , 3D=3)
 Integer,Dimension(1:100)::NFR !Number of  Face of each Regions
 Integer,Dimension(1:100)::BCType !Boundary condition index
 Integer,Dimension(1:Dim)::FaceType !Type of Face (Triangle or Rectangle)
 Integer,Dimension(1:Dim)::CellType !Cell Types
 Integer,Dimension(1:DimIDS,1:Dim)::IDS !Information of Data Structured (1,i):Left Cell,(2,i):Right Cell,(3:FaceType,i):Forming Point of Face
 Real*8,Dimension(1:Dim)::X,Y,Z !Coordinate of Points Constructing Mesh
 Character*100,Dimension(1:100)::BCTitle !Boundary Curve Titles=''
!************************************** Main ***********************************************
!part 1:
 Call ReadMSH(Dim,DimIDS,NP,NC,NF,NR,NFR,IDS,X,Y,Z,BCType,BCTitle,CellType,FaceType,MeshDim)
  
!part 2:
 Call Write3DMeshSepRgn_gid_plt(Dim,NP,NF,NR,NFR,IDS,X,Y,Z,FaceType,"imesh.plt")
 !Call Write2DMeshSepRgn_gid_plt(Dim,NP,NR,NFR,IDS,X,Y,"imesh.plt")
 
!part 3:
 Call WriteMesh_gid(Dim,DimIDS,NP,NC,NF,NR,NFR,IDS,X,Y,Z,BCType,BCTitle,CellType,FaceType,MeshDim)
  
!part 4:
 !!!Call WriteMsh(Dim,DimIDS,NP,NC,NF,NR,NFR,IDS,X,Y,Z,BCType,BCTitle,CellType,FaceType,MeshDim)
!*********************************************************************************************
 End
!###########################################################################################

